import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { DarkThemeToggle, Flowbite } from "flowbite-react";
import toast, { Toaster } from "react-hot-toast";
import AuthProvider from "@/components/Provider";
import { getServerSession } from "next-auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  console.log("seession", session);
  return (
    <html lang="en">
      <Flowbite>
        <body className={`${inter.className} bg-gray-50 dark:bg-slate-950`}>
          <AuthProvider session={session}>
            <Header />
            <Toaster />
            {children}
            <Footer />
          </AuthProvider>
        </body>
      </Flowbite>
    </html>
  );
}
